-- Phase 6 — embedding backend swap: on-device transformers.js CLIP
-- (Xenova/clip-vit-base-patch32, 512-dim) REPLACES the Replicate
-- krthr/clip-embeddings (768-dim) backend.
--
-- WHY: Replicate cold-started (~5-15s) on the first scan after idling — fatal
-- for single-image experiences, which are always a first scan. The query
-- embedding now runs in the browser (public/lib/clip-embed.js), so there is no
-- server round-trip to embed: no cold-start, no per-call cost, no rate limit.
-- The Node seed pipeline embeds with the SAME model so index/query vectors match.
--
-- SCOPE: rebuilds the pop_images index dimension + the search RPC ONLY.
-- pop_images is a DERIVED index — its rows are regenerated by re-running
-- scripts/seed-identification.mjs. Nothing else is touched (collections,
-- collection_items, creators, identify_events all unchanged).
--
-- ORDER OF OPERATIONS:
--   1. Run this in the `identification` BRANCH SQL editor; re-seed; verify.
--   2. At cutover, run the SAME file in PRODUCTION; re-seed prod; verify.
-- The old 768-dim vectors are obsolete the moment the model changes, so this is
-- intentionally destructive to pop_images rows (only).

-- A vector column can't be retyped to a different dimension while rows of the
-- old dimension exist. Drop the dependent RPC first, then clear the rows.
drop function if exists identify_match(uuid, vector, int);

delete from pop_images;

-- Retype embedding 768 -> 512 and rebuild the cosine (ivfflat) index.
drop index if exists pop_images_embedding_idx;
alter table pop_images alter column embedding type vector(512);
create index pop_images_embedding_idx
  on pop_images using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Recreate the scoped nearest-neighbour search with the new dimension.
-- `<=>` is pgvector cosine distance; confidence = 1 - distance (1.0 = identical).
-- ALWAYS scoped to one creator (the privacy wall).
create or replace function identify_match(
  p_creator_id uuid,
  p_embedding  vector(512),
  p_limit      int default 1
)
returns table (
  image_id      uuid,
  collection_id uuid,
  target_ref    text,
  video_url     text,
  confidence    double precision
)
language sql stable
as $$
  select id, collection_id, target_ref, video_url,
         1 - (embedding <=> p_embedding) as confidence
  from pop_images
  where creator_id = p_creator_id
  order by embedding <=> p_embedding
  limit p_limit;
$$;

-- Called only from the server with the service role; not exposed to anon.
grant execute on function identify_match(uuid, vector, int) to service_role;
